[project]
name = "py-backend-analytics"
version = "0.1.0"
description = "easy-to-setup network analytics for python backends"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "maxminddb>=3.1.1",
]

[dependency-groups]
test = [
    "pytest",
    "fastapi",
    "uvicorn",
    "jinja2"
]
