[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-backend-analytics"
version = "0.5.0"
description = "easy-to-setup network analytics for python backends"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.22.1",
    "maxminddb>=3.1.1",
]

[dependency-groups]
test = [
    "pytest",
    "pytest-asyncio",
    "fastapi",
    "uvicorn",
    "jinja2",
    "httpx"
]

[tool.setuptools.package-data]
py_backend_analytics = ["**/*.css", "**/*.html"]
