from py_backend_analytics.db.abstract_db_client import AbstractDBClient


class SQLiteDBClient(AbstractDBClient):
    def insert_request_info(self): ...

    def read_request_info(self): ...

    def create_db_table(self): ...

    def check_db_table_exists(self): ...
